// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg-OIYQM2BbNGo18PRKh1HlR8xw6d73ik',
    appId: '1:156198589336:web:77964970c3ab57862751ed',
    messagingSenderId: '156198589336',
    projectId: 'sample-db11c',
    authDomain: 'sample-db11c.firebaseapp.com',
    storageBucket: 'sample-db11c.firebasestorage.app',
    measurementId: 'G-WZ0B3NLY7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnmo6LQyJzYuQvOMxYNwRhsVWJ0hnPAEY',
    appId: '1:156198589336:android:0a32c390a81956ce2751ed',
    messagingSenderId: '156198589336',
    projectId: 'sample-db11c',
    storageBucket: 'sample-db11c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkYvUwvxUmbsIfRwSFpwIwj-z4p0qPM60',
    appId: '1:156198589336:ios:a0ebcad9e91fface2751ed',
    messagingSenderId: '156198589336',
    projectId: 'sample-db11c',
    storageBucket: 'sample-db11c.firebasestorage.app',
    iosBundleId: 'com.example.todoTaskApp',
  );
}
